nelmio_cors:
    defaults:
        origin_regex: true
        # Autoriser localhost sur n'importe quel port
        allow_origin: ['~^https?://(localhost|127\.0\.0\.1)(:\d+)?$~']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
        expose_headers: ['Link', 'Content-Range']
        max_age: 3600
        allow_credentials: true

    paths:
        '^/api':
            allow_origin: ['~^https?://(localhost|127\.0\.0\.1)(:\d+)?$~']
            allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
            allow_credentials: true
            max_age: 3600

        '^/login':
            allow_origin: ['~^https?://(localhost|127\.0\.0\.1)(:\d+)?$~']
            allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
            allow_methods: ['POST', 'OPTIONS']
            allow_credentials: true
            max_age: 3600

        '^/media':
            allow_origin: ['*']