# Fichier de lien avec l'application front
nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['http://localhost:5173']  # React port par défault , à changer si besoin
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link', 'Content-Range']
        max_age: 3600
    paths:
        '^/api':
            allow_origin: ['http://localhost:3000', 'http://localhost:5173']
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
            max_age: 3600
        '^/media': ~