name: Build & Push Docker Image

on:
  push:
    branches: [ master ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du repo BACK
        uses: actions/checkout@v4

      - name: Login Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build de l'image Docker avec React
        run: |
          docker build \
            --build-arg REACT_REPO_URL="https://github.com/Soifiaouir/AppMuseeTransmitionsReact.git" \
            --build-arg REACT_BRANCH=master \
            -t ${{ secrets.DOCKER_REPOSITORY }}:latest \
            .

      - name: Push de l'image sur Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_REPOSITORY }}:latest

      - name: Confirmation de publication
        run: |
          echo "================================================"
          echo "Image Docker publiee avec succes !"
          echo "Repository: ${{ secrets.DOCKER_REPOSITORY }}"
          echo "Tag: latest"
          echo "================================================"